name: observer
description: Basic dart only observer pattern.
version: 1.0.0
homepage: https://github.com/antonkesy/observer.dart
repository: https://github.com/antonkesy/observer.dart

environment:
  sdk: ">=2.15.1 <3.0.0"

dev_dependencies:
  test: any